/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TestResult = IDL.Variant({
  'indeterminate' : IDL.Null,
  'negative' : IDL.Null,
  'positive' : IDL.Null,
});
export const TestType = IDL.Variant({
  'pcr' : IDL.Null,
  'rdt' : IDL.Null,
  'culture' : IDL.Null,
  'elisa' : IDL.Null,
});
export const LabResult = IDL.Record({
  'result' : TestResult,
  'testType' : TestType,
  'collectionDate' : IDL.Text,
  'labName' : IDL.Text,
});
export const Disease = IDL.Variant({
  'yellowFever' : IDL.Null,
  'mpox' : IDL.Null,
  'meningitis' : IDL.Null,
  'marburg' : IDL.Null,
  'ebola' : IDL.Null,
  'covid19' : IDL.Null,
  'lassaFever' : IDL.Null,
  'cholera' : IDL.Null,
});
export const ClinicalOutcome = IDL.Variant({
  'alive' : IDL.Null,
  'dead' : IDL.Null,
  'unknown' : IDL.Null,
});
export const AnalyticsSummary = IDL.Record({
  'weeklyCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'casesByDisease' : IDL.Vec(IDL.Tuple(Disease, IDL.Nat)),
  'casesByOutcome' : IDL.Vec(IDL.Tuple(ClinicalOutcome, IDL.Nat)),
  'casesByAgeGroup' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'casesBySex' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'casesByState' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'organization' : IDL.Text,
});
export const CaseStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const PatientDemographics = IDL.Record({
  'age' : IDL.Nat,
  'lga' : IDL.Text,
  'sex' : IDL.Text,
  'state' : IDL.Text,
});
export const CaseClassification = IDL.Variant({
  'probable' : IDL.Null,
  'suspected' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const CaseReport = IDL.Record({
  'id' : IDL.Nat,
  'status' : CaseStatus,
  'exposureHistory' : IDL.Text,
  'symptomsDate' : IDL.Text,
  'timestamp' : Time,
  'disease' : Disease,
  'labResult' : IDL.Opt(LabResult),
  'outcome' : ClinicalOutcome,
  'reporter' : IDL.Principal,
  'demographics' : PatientDemographics,
  'classification' : CaseClassification,
});
export const AlertLevel = IDL.Variant({
  'warning' : IDL.Null,
  'emergency' : IDL.Null,
  'watch' : IDL.Null,
});
export const OutbreakAlert = IDL.Record({
  'caseCount' : IDL.Nat,
  'alertLevel' : AlertLevel,
  'state' : IDL.Text,
  'disease' : Disease,
  'weekStart' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveReport' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'attachLabResult' : IDL.Func([IDL.Nat, LabResult], [], []),
  'getAnalyticsSummary' : IDL.Func([], [AnalyticsSummary], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCaseById' : IDL.Func([IDL.Nat], [CaseReport], ['query']),
  'getCaseReports' : IDL.Func(
      [IDL.Opt(Disease), IDL.Opt(IDL.Text)],
      [IDL.Vec(CaseReport)],
      ['query'],
    ),
  'getOutbreakAlerts' : IDL.Func([], [IDL.Vec(OutbreakAlert)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectReport' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitCaseReport' : IDL.Func(
      [
        PatientDemographics,
        Disease,
        CaseClassification,
        IDL.Text,
        IDL.Text,
        ClinicalOutcome,
      ],
      [IDL.Nat],
      [],
    ),
  'updateCaseReport' : IDL.Func(
      [
        IDL.Nat,
        PatientDemographics,
        Disease,
        CaseClassification,
        IDL.Text,
        IDL.Text,
        ClinicalOutcome,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TestResult = IDL.Variant({
    'indeterminate' : IDL.Null,
    'negative' : IDL.Null,
    'positive' : IDL.Null,
  });
  const TestType = IDL.Variant({
    'pcr' : IDL.Null,
    'rdt' : IDL.Null,
    'culture' : IDL.Null,
    'elisa' : IDL.Null,
  });
  const LabResult = IDL.Record({
    'result' : TestResult,
    'testType' : TestType,
    'collectionDate' : IDL.Text,
    'labName' : IDL.Text,
  });
  const Disease = IDL.Variant({
    'yellowFever' : IDL.Null,
    'mpox' : IDL.Null,
    'meningitis' : IDL.Null,
    'marburg' : IDL.Null,
    'ebola' : IDL.Null,
    'covid19' : IDL.Null,
    'lassaFever' : IDL.Null,
    'cholera' : IDL.Null,
  });
  const ClinicalOutcome = IDL.Variant({
    'alive' : IDL.Null,
    'dead' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const AnalyticsSummary = IDL.Record({
    'weeklyCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'casesByDisease' : IDL.Vec(IDL.Tuple(Disease, IDL.Nat)),
    'casesByOutcome' : IDL.Vec(IDL.Tuple(ClinicalOutcome, IDL.Nat)),
    'casesByAgeGroup' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'casesBySex' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'casesByState' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'organization' : IDL.Text,
  });
  const CaseStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const PatientDemographics = IDL.Record({
    'age' : IDL.Nat,
    'lga' : IDL.Text,
    'sex' : IDL.Text,
    'state' : IDL.Text,
  });
  const CaseClassification = IDL.Variant({
    'probable' : IDL.Null,
    'suspected' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const CaseReport = IDL.Record({
    'id' : IDL.Nat,
    'status' : CaseStatus,
    'exposureHistory' : IDL.Text,
    'symptomsDate' : IDL.Text,
    'timestamp' : Time,
    'disease' : Disease,
    'labResult' : IDL.Opt(LabResult),
    'outcome' : ClinicalOutcome,
    'reporter' : IDL.Principal,
    'demographics' : PatientDemographics,
    'classification' : CaseClassification,
  });
  const AlertLevel = IDL.Variant({
    'warning' : IDL.Null,
    'emergency' : IDL.Null,
    'watch' : IDL.Null,
  });
  const OutbreakAlert = IDL.Record({
    'caseCount' : IDL.Nat,
    'alertLevel' : AlertLevel,
    'state' : IDL.Text,
    'disease' : Disease,
    'weekStart' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveReport' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'attachLabResult' : IDL.Func([IDL.Nat, LabResult], [], []),
    'getAnalyticsSummary' : IDL.Func([], [AnalyticsSummary], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCaseById' : IDL.Func([IDL.Nat], [CaseReport], ['query']),
    'getCaseReports' : IDL.Func(
        [IDL.Opt(Disease), IDL.Opt(IDL.Text)],
        [IDL.Vec(CaseReport)],
        ['query'],
      ),
    'getOutbreakAlerts' : IDL.Func([], [IDL.Vec(OutbreakAlert)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectReport' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitCaseReport' : IDL.Func(
        [
          PatientDemographics,
          Disease,
          CaseClassification,
          IDL.Text,
          IDL.Text,
          ClinicalOutcome,
        ],
        [IDL.Nat],
        [],
      ),
    'updateCaseReport' : IDL.Func(
        [
          IDL.Nat,
          PatientDemographics,
          Disease,
          CaseClassification,
          IDL.Text,
          IDL.Text,
          ClinicalOutcome,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };