/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ArticleStatus = IDL.Variant({
  'underReview' : IDL.Null,
  'published' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const JournalArticle = IDL.Record({
  'id' : IDL.Nat,
  'pdf' : ExternalBlob,
  'status' : ArticleStatus,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'authors' : IDL.Vec(IDL.Text),
  'publicationDate' : IDL.Opt(Time),
  'journalName' : IDL.Text,
  'abstract' : IDL.Text,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'organization' : IDL.Text,
});
export const ReviewerApplication = IDL.Record({
  'institution' : IDL.Text,
  'name' : IDL.Text,
  'qualifications' : IDL.Text,
  'email' : IDL.Text,
  'expertise' : IDL.Vec(IDL.Text),
});
export const ManuscriptSubmission = IDL.Record({
  'id' : IDL.Nat,
  'status' : ArticleStatus,
  'title' : IDL.Text,
  'authors' : IDL.Vec(IDL.Text),
  'contactEmail' : IDL.Text,
  'abstract' : IDL.Text,
  'category' : IDL.Text,
  'manuscriptFile' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getArticleById' : IDL.Func([IDL.Nat], [IDL.Opt(JournalArticle)], ['query']),
  'getArticles' : IDL.Func([], [IDL.Vec(JournalArticle)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedArticles' : IDL.Func([], [IDL.Vec(JournalArticle)], ['query']),
  'getLatestArticles' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(JournalArticle)],
      ['query'],
    ),
  'getPaperStatus' : IDL.Func([IDL.Nat], [IDL.Opt(ArticleStatus)], ['query']),
  'getReviewerApplications' : IDL.Func(
      [],
      [IDL.Vec(ReviewerApplication)],
      ['query'],
    ),
  'getSubmissions' : IDL.Func([], [IDL.Vec(ManuscriptSubmission)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishArticle' : IDL.Func(
      [IDL.Nat, IDL.Text, Time, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'registerReviewer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setFeatured' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'submitManuscript' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Nat],
      [],
    ),
  'updatePaperStatus' : IDL.Func([IDL.Nat, ArticleStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ArticleStatus = IDL.Variant({
    'underReview' : IDL.Null,
    'published' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const JournalArticle = IDL.Record({
    'id' : IDL.Nat,
    'pdf' : ExternalBlob,
    'status' : ArticleStatus,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'authors' : IDL.Vec(IDL.Text),
    'publicationDate' : IDL.Opt(Time),
    'journalName' : IDL.Text,
    'abstract' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'organization' : IDL.Text,
  });
  const ReviewerApplication = IDL.Record({
    'institution' : IDL.Text,
    'name' : IDL.Text,
    'qualifications' : IDL.Text,
    'email' : IDL.Text,
    'expertise' : IDL.Vec(IDL.Text),
  });
  const ManuscriptSubmission = IDL.Record({
    'id' : IDL.Nat,
    'status' : ArticleStatus,
    'title' : IDL.Text,
    'authors' : IDL.Vec(IDL.Text),
    'contactEmail' : IDL.Text,
    'abstract' : IDL.Text,
    'category' : IDL.Text,
    'manuscriptFile' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getArticleById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(JournalArticle)],
        ['query'],
      ),
    'getArticles' : IDL.Func([], [IDL.Vec(JournalArticle)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedArticles' : IDL.Func([], [IDL.Vec(JournalArticle)], ['query']),
    'getLatestArticles' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(JournalArticle)],
        ['query'],
      ),
    'getPaperStatus' : IDL.Func([IDL.Nat], [IDL.Opt(ArticleStatus)], ['query']),
    'getReviewerApplications' : IDL.Func(
        [],
        [IDL.Vec(ReviewerApplication)],
        ['query'],
      ),
    'getSubmissions' : IDL.Func([], [IDL.Vec(ManuscriptSubmission)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishArticle' : IDL.Func(
        [IDL.Nat, IDL.Text, Time, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'registerReviewer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setFeatured' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'submitManuscript' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          ExternalBlob,
        ],
        [IDL.Nat],
        [],
      ),
    'updatePaperStatus' : IDL.Func([IDL.Nat, ArticleStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };