/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AlertLevel = { 'warning' : null } |
  { 'emergency' : null } |
  { 'watch' : null };
export interface AnalyticsSummary {
  'weeklyCounts' : Array<[string, bigint]>,
  'casesByDisease' : Array<[Disease, bigint]>,
  'casesByOutcome' : Array<[ClinicalOutcome, bigint]>,
  'casesByAgeGroup' : Array<[string, bigint]>,
  'casesBySex' : Array<[string, bigint]>,
  'casesByState' : Array<[string, bigint]>,
}
export type CaseClassification = { 'probable' : null } |
  { 'suspected' : null } |
  { 'confirmed' : null };
export interface CaseReport {
  'id' : bigint,
  'status' : CaseStatus,
  'exposureHistory' : string,
  'symptomsDate' : string,
  'timestamp' : Time,
  'disease' : Disease,
  'labResult' : [] | [LabResult],
  'outcome' : ClinicalOutcome,
  'reporter' : Principal,
  'demographics' : PatientDemographics,
  'classification' : CaseClassification,
}
export type CaseStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ClinicalOutcome = { 'alive' : null } |
  { 'dead' : null } |
  { 'unknown' : null };
export type Disease = { 'yellowFever' : null } |
  { 'mpox' : null } |
  { 'meningitis' : null } |
  { 'marburg' : null } |
  { 'ebola' : null } |
  { 'covid19' : null } |
  { 'lassaFever' : null } |
  { 'cholera' : null };
export interface LabResult {
  'result' : TestResult,
  'testType' : TestType,
  'collectionDate' : string,
  'labName' : string,
}
export interface OutbreakAlert {
  'caseCount' : bigint,
  'alertLevel' : AlertLevel,
  'state' : string,
  'disease' : Disease,
  'weekStart' : Time,
}
export interface PatientDemographics {
  'age' : bigint,
  'lga' : string,
  'sex' : string,
  'state' : string,
}
export type TestResult = { 'indeterminate' : null } |
  { 'negative' : null } |
  { 'positive' : null };
export type TestType = { 'pcr' : null } |
  { 'rdt' : null } |
  { 'culture' : null } |
  { 'elisa' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'organization' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveReport' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'attachLabResult' : ActorMethod<[bigint, LabResult], undefined>,
  'getAnalyticsSummary' : ActorMethod<[], AnalyticsSummary>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCaseById' : ActorMethod<[bigint], CaseReport>,
  'getCaseReports' : ActorMethod<
    [[] | [Disease], [] | [string]],
    Array<CaseReport>
  >,
  'getOutbreakAlerts' : ActorMethod<[], Array<OutbreakAlert>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectReport' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitCaseReport' : ActorMethod<
    [
      PatientDemographics,
      Disease,
      CaseClassification,
      string,
      string,
      ClinicalOutcome,
    ],
    bigint
  >,
  'updateCaseReport' : ActorMethod<
    [
      bigint,
      PatientDemographics,
      Disease,
      CaseClassification,
      string,
      string,
      ClinicalOutcome,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];